services:
  # app : (php 7.4 / laravel 8)
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 82:80
    volumes:
      - ../src:/var/www/html
      - ./config/laravel-app/.env:/var/www/html/.env
      - ./config/laravel-app/.env.testing:/var/www/html/.env.testing
      - devcorp-app-vendor:/var/www/html/vendor
    networks:
      - devcorp-net
  # db : (postgres-db 15)
  db:
    image: postgres:15
    ports:
      - 5433:5432 # Note : app/adminer services use devcorp-net network (host:db/port:5432)
    environment:
      POSTGRES_USER: postgres # default user
      POSTGRES_PASSWORD: root
      #POSTGRES_DB: devcorp-db # see postgres-db/init.sql
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./config/postgres-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devcorp-net
  # adminer (for : db service)
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - devcorp-net

volumes:
  # for app dependencies (vendor)
  devcorp-app-vendor:


networks:
  devcorp-net:
    driver: bridge
